apiVersion: v1
kind: Service
metadata:
  name: vsftpd-pub-svc
  namespace: mosson
spec:
  type: ClusterIP
  selector:
    app: vsftpd-pub
  ports:
    - name: ftp-transfer
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 22
    - name: pasv-4559
      protocol: TCP
      port: 4565
      targetPort: 4565
    - name: pasv-4560
      protocol: TCP
      port: 4566
      targetPort: 4566
    - name: pasv-4561
      protocol: TCP
      port: 4567
      targetPort: 4567
    - name: pasv-4562
      protocol: TCP
      port: 4568
      targetPort: 4568
    - name: pasv-4563
      protocol: TCP
      port: 4569
      targetPort: 4569
    - name: pasv-4564
      protocol: TCP
      port: 4570
      targetPort: 4570

---

apiVersion: v1
kind: Service
metadata:
  name: vsftpd-pri-svc
  namespace: mosson
spec:
  type: ClusterIP
  selector:
    app: vsftpd-pri
  ports:
    - name: ftp-transfer
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 22
    - name: pasv-4559
      protocol: TCP
      port: 4559
      targetPort: 4559
    - name: pasv-4560
      protocol: TCP
      port: 4560
      targetPort: 4560
    - name: pasv-4561
      protocol: TCP
      port: 4561
      targetPort: 4561
    - name: pasv-4562
      protocol: TCP
      port: 4562
      targetPort: 4562
    - name: pasv-4563
      protocol: TCP
      port: 4563
      targetPort: 4563
    - name: pasv-4564
      protocol: TCP
      port: 4564
      targetPort: 4564
